version: 1
formatters:
  simple:
    format: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
  colorlog:
    "()": "colorlog.ColoredFormatter"
    format: "[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s"
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
    level: INFO
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    level: DEBUG

loggers:
  __main__:
    handlers: [console, file]
  mcd:
    handlers: [console, file]

root:
  level: NOTSET

disable_existing_loggers: false
